### ISSUE TITLE
Crashes once starting interpolation process.

### ISSUE THREAD

**Issue by davFaithid** [baowenbo/DAIN#101]
ffmpeg extracts all of the frames, yet once starting the interpolation process, DAIN just closes itself without an explanation. 

I was able to stop from crashing long enough to get the log:
```
F:/Alienware Backup/D/Desktop/dain/detectiveconan002/frames.json
Main Folder: F:/Alienware Backup/D/Desktop/dain/detectiveconan002/
Starting PNG frames extraction!
Finished PNG frames extraction!
Starting Interpolation!
  0%|                                                 | 0/24854 [00:00<?, ?it/s]
```
Any help would be greatly appreciated.

**Comment by AlphaGit** [comment]
Hi there! I think you might be using DAINApp, but that's not being developed here. DAIN is the underlying ML behind it. You might want to check the DAINApp Discord, they'll probably be able to help you there.
