### ISSUE TITLE
Colab interpolation error

### ISSUE THREAD

**Issue by amerfathullah** [baowenbo/DAIN#102]
*DAIN Colab, v1.4.0*

colab assigned GPU
name, driver_version, memory.total [MiB]
Tesla P100-PCIE-16GB, 418.67, 16280 MiB

# Interpolation

/content/DAIN
revise the unique id to a random numer 9776
Namespace(SAVED_MODEL=None, alpha=[0.0, 1.0], arg='./model_weights/9776-Thu-Sep-17-11-06/args.txt', batch_size=1, channels=3, ctx_lr_coe=1.0, datasetName='Vimeo_90K_interp', datasetPath='', dataset_split=97, debug=False, depth_lr_coe=0.001, dtype=<class 'torch.cuda.FloatTensor'>, end_frame=5682, epsilon=1e-06, factor=0.2, filter_lr_coe=1.0, filter_size=4, flow_lr_coe=0.01, force=False, frame_input_dir='/content/DAIN/input_frames', frame_output_dir='/content/DAIN/output_frames', log='./model_weights/9776-Thu-Sep-17-11-06/log.txt', lr=0.002, netName='DAIN_slowmotion', no_date=False, numEpoch=100, occ_lr_coe=1.0, patience=5, rectify_lr=0.001, save_path='./model_weights/9776-Thu-Sep-17-11-06', save_which=1, seed=1, start_frame=1, time_step=0.5051555555555556, uid=None, use_cuda=True, use_cudnn=1, weight_decay=0, workers=8)
cudnn is used
Interpolate 0 frames
Traceback (most recent call last):
  File "colab_interpolate.py", line 112, in <module>
    y_s, offset, filter = model(torch.stack((X0, X1),dim = 0))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/DAIN/networks/DAIN_slowmotion.py", line 202, in forward
    return cur_outputs,cur_offset_output,cur_filter_output
UnboundLocalError: local variable 'cur_offset_output' referenced before assignment

please help me with this issue

**Comment by AlphaGit** [comment]
@AlphaGit Hi! I think I might be able to look into this issue. Do you have a source file and the set of options that helps reproduce this issue?

**Comment by AlphaGit** [comment]
@amerfathullah  Hi! I think I might be able to look into this issue. Do you have a source file and the set of options that helps reproduce this issue?

Also, note that the "Interpolate 0 frames" is a giveaway that the current settings will not work. That means that between frame1 and frame2, 0 frames will be created. This means that your setting will not generate any new frames for you. Play around with the FPS settings.
