### ISSUE TITLE
When I run the 2nd command from the Readme, I get the error „No module named torch”

### ISSUE THREAD

**Issue by Sosasees** [baowenbo/DAIN#105]
When I run the 2nd command from the [Readme](../blob/master/README.md), the command being

> `python -c "import torch; print(torch.__version__)"`

, I get this error as the output of the command:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named torch

. How do I fix this error so that I can install DAIN on my Linux Computer?

**Comment by AlphaGit** [comment]
@Sosasees Hi! That step is to verify that you have PyTorch as a module available. The error demonstrates that you don't. As such, you'd need to install PyTorch 1.0.0 or above.

**Comment by iBobbyTS** [comment]
pip install torch==1.4.0

PyTorch 1.4 is the latest version compile with DAIN, it's faster than 1.0.0

**Comment by Sosasees** [comment]
Thanks for the Installation Command.
I must've taken a break not long enough, because I didn't see it at the beginning of the Readme.

**Comment by iBobbyTS** [comment]
In the README, it says it needs to be torch>=1.0.0. Torch 1.5.0 causes errors when building CUDAExtension. Torch 1.4.0 works, and it does a faster job than 1.0.0. There will be warnings in 1.4.0, just use a warning filter to remove them, not a big deal.
