### ISSUE TITLE
About the PSNR

### ISSUE THREAD

**Issue by 1145520074** [baowenbo/DAIN#11]
I have a question when I read your paper.In your paper the DVF method's PSNR is 34.12. But in the DVF original paper the PSNR is 35.8. So, what's your evaluate method?

**Comment by baowenbo** [comment]
I think there is be a discrepancy between the results reported in DVF's paper and the results generated by DVF's [released code](https://github.com/liuziwei7/voxel-flow).
You might try their code as well.
