### ISSUE TITLE
Unusing frames hang in memory

### ISSUE THREAD

**Issue by Borshig** [baowenbo/DAIN#111]
![ScreenDainAPP](https://user-images.githubusercontent.com/17796364/97907719-bcfca900-1d56-11eb-885c-82fe21683830.PNG)
i can't process 20 minutes video because all processed frames remain in memory and there is no free space for a new frame. 
as you say "Only VRAM using in DAINAPP" wtf?

**Comment by AlphaGit** [comment]
Hi there! You might be thinking of DainApp, which is developed [here](https://grisk.itch.io/dain-app) or [here](https://www.patreon.com/DAINAPP). This repository and work is about the neural networks that power the functionality. This is not the program that you are using.
