### ISSUE TITLE
Please provide SSIM evaluation code

### ISSUE THREAD

**Issue by HopLee6** [baowenbo/DAIN#12]
The results on SSIM cannot be reproduced. Please provide your SSIM code.

**Comment by baowenbo** [comment]
Note that for all SSIM numbers in the tables, I do not use the Python's `compares_ssim` tool but I use the Matlab's `ssim()` function on the generated images. Is this your case?

**Comment by HopLee6** [comment]
I have try `ssim()` in matlab and the results are the same as reported ones.
The results are higher than those computed by Python's `compares_ssim()` because the computation of SSIM on color images are different.
Thx.

**Comment by baowenbo** [comment]
Cool. Thank you.

**Comment by zhhezhhe** [comment]
@HopLee6 @baowenbo I also can not get the same ssim value as reported ones. I use the matlab code https://github.com/liuziwei7/voxel-flow/blob/master/eval_voxelflow.m

I try different input of the ssim() In my code
```
[ssim_cur, ~] = ssim(rgb2gray(uint8(img_pred_mask)), rgb2gray(uint8(img_target_mask)));
[ssim_cur, ~] = ssim(rgb2gray(uint8(img_pred)), rgb2gray(uint8(img_target)));
[ssim_cur, ~] = ssim(img_pred, img_target);
```
But I can not get the ssim value = 0.9683 of UCF101, ssim = 0.9756 of Vimeo90K.
Could you please provide some code examples?

**Comment by baowenbo** [comment]
I followed exactly ToFlow's [evaluation.m](https://github.com/anchen1011/toflow/blob/master/src/evaluation/evaluate.m) code.

**Comment by zhhezhhe** [comment]
Thanks a lot!
