### ISSUE TITLE
'int' object has no attribute 'zfill'

### ISSUE THREAD

**Issue by kindvy** [baowenbo/DAIN#139]
Here i try to make my old video with 3gp extension from 30 fps become 120 fps and i use ipynb version. i got these error at "ffmpeg extract - Generating individual frame PNGs from the source file" section. I don't know how to fix this error ('int' object has no attribute 'zfill').

**Comment by AlphaGit** [comment]
Hi! Sorry you had that issue. That seems to be an actual bug in the python notebook code. You can solve it with one of those two ways:

Option 1: turn off the seamless option. This way, the faulty code will not execute. 

Option 2: in the notebook, replace this line:

```python
  new_last_frame = f"{FRAME_INPUT_DIR}/{frame_count.zfill(5)}.png"
```

By this line:

```python
  new_last_frame = f"{FRAME_INPUT_DIR}/{str(frame_count).zfill(5)}.png"
```

(The two spaces at the beginning of the line are important.)

I hope this helps!
