### ISSUE TITLE
Is there a way to run/install this on Anaconda on windows?

### ISSUE THREAD

**Issue by deama** [baowenbo/DAIN#14]
Can I get this running on Windows with anaconda? I installed the required packages, but I don't know how to get the ./build.sh thing working.

**Comment by baowenbo** [comment]
I never tried on Windows. You'd better use a Ubuntu.

**Comment by buildist** [comment]
I got DAIN to run on Windows with Python 3.6.8, Pytorch 1.1.0, CUDA 10.1 and Visual Studio 14.0.

Had to make a few small changes:
- for each extension, update setup.py to add `-D__CUDA_NO_HALF_OPERATORS__`  to the nvcc_args (https://github.com/torch/cutorch/issues/797)
- for each extension, update the *.cc file to replace `#include <torch/torch.h>` with `#include <torch/extension.h>`
- replace : with any other character in https://github.com/baowenbo/DAIN/blob/master/my_args.py#L77 (not allowed in Windows paths)
- didn't try to use the build.sh scripts, just cd into each extension directory and run `python setup.py install`
