### ISSUE TITLE
Can you provide IE evaluation code?

### ISSUE THREAD

**Issue by mrchizx** [baowenbo/DAIN#16]
Can you provide a sample code for calculating IE for color images? I cannot get the same number for Middlebury other dataset.

**Comment by baowenbo** [comment]
`rec_rgb =  imread(arguments_strOut)`
`gt_rgb = imread(gt_path)`
`diff_rgb = rec_rgb - gt_rgb`
`interp_error = np.mean(np.abs(diff_rgb))`
