### ISSUE TITLE
training strategy

### ISSUE THREAD

**Issue by hhhhhumengshun** [baowenbo/DAIN#2]
can you share train.py code?  i don't understand training strategy. thanks

**Comment by hhqweasd** [comment]
同求

**Comment by jinsc37** [comment]
I would like it as well

**Comment by l2009312042** [comment]
yes ， i like it ,and can you share  the memc-net  source code ?

**Comment by mwy691222563** [comment]
thx

**Comment by zhhezhhe** [comment]
thx

**Comment by baowenbo** [comment]
Hi guys, see the updated [Training New Models](https://github.com/baowenbo/DAIN#training-new-models).

**Comment by baowenbo** [comment]
> yes ， i like it ,and can you share the memc-net source code ?

MEMC-Net is also published. 

https://github.com/baowenbo/MEMC-Net
