### ISSUE TITLE
What is the exact network size for Kernel Estimation Module?

### ISSUE THREAD

**Issue by mrchizx** [baowenbo/DAIN#20]
I was curious about the number of paramters for the 1d kernel estimation network. In the paper, it states that this sub module has 5.51M of paramters. However, when I look at the kernel estimation network structure in the supplemental material, I believe it is much larger than 5.51M. In the decoder, one layer with 4x4x512x512 already has around 4.19M parameters.

![image](https://user-images.githubusercontent.com/44560648/63991329-48284200-cab5-11e9-9865-3bd801571e0b.png)

**Comment by laomao0** [comment]
You are so careful, so am I.
I found the problem too.

The method of calculating the net parameters is right, maybe the author was forgotten to modify the text in the paper.

We check  DAIN/networks/DAIN.py/, the Kernel Esti model is created by function: get_MonoNet5
 
You need to calculate the parameter use this net.

That is why the author share his code.

**Comment by mrchizx** [comment]
Oh.. OK, that makes sense. I am very sensitive to the model sizes, that's the reason of being careful.

**Comment by Bello64** [comment]
> Oh.. OK, that makes sense. I am very sensitive to the model sizes, that's the reason of being careful.

I can't find the supplemental material. Can you tell me where I can find it.
