### ISSUE TITLE
Can DAIN directly process the raw video?

### ISSUE THREAD

**Issue by Rimay** [baowenbo/DAIN#26]
The demo script given in the repo require two frames as input, however, can the DAIN directly choose a  video as input and output the corresponding synthesis video?
or does anyone has written the script to do so?

**Comment by laomao0** [comment]
The simple method is to use ffmpeg.
First, decode the video to frames, then use dain to do interpolation.
After processing, use ffmpeg again to encode the whole frames.
There is a script you can refer to https://github.com/avinashpaliwal/Super-SloMo/blob/master/video_to_slomo.py.
