### ISSUE TITLE
Interpolation error

### ISSUE THREAD

**Issue by saikatdutta** [baowenbo/DAIN#27]
https://github.com/baowenbo/DAIN/blob/4dbb134b61af751a1871ab7320be23d191ea4664/demo_MiddleBury.py#L169

Shouldn't the Interpolation error be RMSE instead of L1 distance?

**Comment by laomao0** [comment]
L1 or L2 distance are two similar metrics for calculating IE.
The author computes the middlebury-other dataset with gt to reflect the performance.
The Middlebury website may use RMSE to compute IE, please refer to the Middlebury website for more information.
