### ISSUE TITLE
关于深度图的问题

### ISSUE THREAD

**Issue by hhqweasd** [baowenbo/DAIN#3]
你好，深度图确实有用吗？我看消融实验加了深度图只高了0.06分？能提供 得分 vs. 迭代 曲线吗？想入坑这个方向，发现这个方向的问题应该是运动估计的问题，你有什么建议吗？

**Comment by baowenbo** [comment]
It do works, I didn't try too hard to get the cheerful results. 
In Table 4,  you can see that my results is about 0.42dB better on Vimeo90K when comparing to my MEMC-Net method that does not take use of depth.

**Comment by coolKeen** [comment]
> It does work, I didn't try too hard to get the cheerful results.
> In Table 4, you can see that my results is about 0.42dB better on Vimeo90K when comparing to my MEMC-Net method that does not take use of depth.

Could you please publish a version of DAIN without depth information?
