### ISSUE TITLE
Fix BibTeX citation on website

### ISSUE THREAD

**Issue by rivermont** [baowenbo/DAIN#33]
The paper citation on the Google Sites page reads ([link](https://sites.google.com/view/wenbobao/dain#h.p_4dji6RlIuuck)),

> booktitle = {IEEE Conferene on Computer Vision and Pattern Recognition},

"Conferene" should be "Conference". The same typo was in README.md but is fixed in #32.

**Comment by baowenbo** [comment]
Thank you. Fixed now.
