### ISSUE TITLE
Out of memory Issues

### ISSUE THREAD

**Issue by Ristellise** [baowenbo/DAIN#36]
I noticed that DAIN doesn't handle HD video sizes [1280x720] with a 8gb of GPU memory. Running on a GTX 1070. Is there anyway for me to reduce the memory usage on the GPU side?

**Comment by laomao0** [comment]
There is a method which costs more time.
You can first split the image into multiple patches, then run the interpolation process for each patch.
Finally, you need to combine those patches to the whole image.

**Comment by Ristellise** [comment]
> There is a method which costs more time.
You can first split the image into multiple patches, then run the interpolation process for each patch.
Finally, you need to combine those patches to the whole image.

Thanks for replying, so Is it a simple case of splitting the image into a smaller resolution and then rendering each individually with the next frame?

**Comment by laomao0** [comment]
https://github.com/laomao0/EDVR_4K_HDR/blob/master/test_4k_hdr_with_GT_stitching.py

You can refer my case.
I use the EDVR to upconvert the image resolution from 540p to 4k.
The model costs too much gpu memory.
So I split the 540p into 9 sub-images，and runs for each sub-image.
At last, I combine them to form a whole pic.

**Comment by Ristellise** [comment]
Thanks :)
