### ISSUE TITLE
permission denied when i run build.sh

### ISSUE THREAD

**Issue by shikelearn** [baowenbo/DAIN#38]
permission denied when i run build.sh,  how can i solve this problem?

**Comment by laomao0** [comment]
chmod u+x build.sh

**Comment by sngyo** [comment]
For me, the message was `error: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/easy-install.pth'`.

`chmod u+x build.sh` does not work in this case because it just adds execute permission to the user.

I resolved the error by simply adding `sudo`.

```bash
sudo ./build.sh
```
