### ISSUE TITLE
in cu file ,such compare   float down_temp = 0.0f;             while(down_temp == 0.0f && down_offset + 1 <= h - 1 )  is ok?

### ISSUE THREAD

**Issue by l2009312042** [baowenbo/DAIN#4]
down_temp == 0.0f ?

**Comment by l2009312042** [comment]
int left_offset = w_i;            float left_temp = 0.0f;
            while(left_temp ==0.0f && left_offset - 1 >= 0){
                left_offset = left_offset - 1;
                left_temp = count[batch_i * count_b_stride + 0 + h_i * count_h_stride + left_offset] ;
            }
and the search is continue to the left if the value left_temp is zero ,this beyond the four neighbor？

**Comment by baowenbo** [comment]
We search until the left_temp is not zero. 
Once left_temp > 0.0f, we break out.
