### ISSUE TITLE
Scipy no longer supports imread/imwrite, need to use imageio

### ISSUE THREAD

**Issue by vade** [baowenbo/DAIN#42]
Using newer SciPy (which is an unlisted requirement btw), needs changes to some code to not use scipy.misc.imread etc, and rather use http://imageio.github.io

**Comment by NexonSU** [comment]
Workaround:
pip install scipy==1.1.0

**Comment by baowenbo** [comment]
> Workaround:
> pip install scipy==1.1.0

Thanks bro.

**Comment by rgries** [comment]
> Workaround:
> pip install scipy==1.1.0

Note:
This may require to install a Fortran compiler if you don't have  one.

**Comment by shaibagon** [comment]
If you use conda, then
```
conda install scipy=1.1.0
```
also works.

**Comment by buildist** [comment]
Alternatively, I just replaced scipy with imageio in line 13 of demo_MiddleBury.py and everything worked without having to install any old packages.
