### ISSUE TITLE
RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.cc:80)

### ISSUE THREAD

**Issue by rastaman7** [baowenbo/DAIN#48]
I get this error:

RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.cc:80)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fa66bef6193 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: correlation_forward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int) + 0x5ea (0x7fa6694c0d4a in /opt/conda/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1e9b4 (0x7fa6694d19b4 in /opt/conda/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1b870 (0x7fa6694ce870 in /opt/conda/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_do_forward(THPFunction*, _object*) + 0x4ac (0x7fa6b72d0fec in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

when running
CUDA_VISIBLE_DEVICES=0 python demo_MiddleBury.py

Anybody else get this error?
Also, does anybody know how to fix this issue?

**Comment by laomao0** [comment]
Have you compiled the packages in the folder: my_packages?
If not, this may be your CUDA version is not compilable with your PyTorch version.
Check your cuda version by:
$ python
$ import torch
$ print('torch.version.cuda')

then check your installed pytorch version supports the cuda or not?
If not, re-install the pytorch, then re-compile the cuda codes in my_packages.

**Comment by 11menghuan11** [comment]
I also get this error,

what's more, I have compiled the packages in the folder: my_packages;
and  my installed pytorch version supports the cuda (CUDA=10.1.243,pytorch=1.3.1)

Does CUDA have to be 9.0?(or does pytorch have to be '<=1.2.0'

**Comment by PigPage** [comment]
You can try to commented out the checking error code in correlation_cuda.cc.
See details in [https://github.com/NVIDIA/flownet2-pytorch/issues/114](url)

**Comment by baowenbo** [comment]
> and my installed pytorch version supports the cuda (CUDA=10.1.243,pytorch=1.3.1)

The cffi extension of pytorch is varying between version 1.0 and 1.2. So there might be also changes in 1.3.1. You can check out the pytorch1.2.0 branch for reference.
