### ISSUE TITLE
Pytorch 1.2.0 with Python 3.6.8

### ISSUE THREAD

**Issue by DrAutissimo** [baowenbo/DAIN#49]
Hello, 

I am a bit unexperienced with Linux/Ubuntu, so this might be entirely me misunderstanding the requirements.
But as far as I understand, Pytorch 1.2.0 requires a Python version above 3.7? And also there is no Pytorch 1.2.0 version for CUDA 9.0?
Are the versions needed to be exactly what you wrote, or just at least that?
Again, this is probably me being a bit slow, but I would be grateful for an answer in any case.

**Comment by laomao0** [comment]
It just ok. Make sure the Pytorch>=1.0.0.

**Comment by DrAutissimo** [comment]
Is the CUDA version also irrelevant as long as it's compatible with Pytorch?

**Comment by baowenbo** [comment]
Yes.

> Is the CUDA version also irrelevant as long as it's compatible with Pytorch?

Yes
