### ISSUE TITLE
Possible Enhancements: Usage of quad-frames instead of bi-frames

### ISSUE THREAD

**Issue by DonaldTsang** [baowenbo/DAIN#57]
Here is a possible way of improving DAIN:
Instead of getting frame X-1 and frame X+1 to get frame X, what about frames X-3, X-1, X+1 and X+3?
With that it can enhance accuracy by acquiring more context, but that leads to some problems:
what if some of the frames are from different scenes? what should it do?
Are there already scene identification for bi-frame interpolation within DAIN?

**Comment by baowenbo** [comment]
It surely can benefit from more source images. You can find some from [Xiangyu's paper](https://arxiv.org/abs/1911.00627) or [my previous work](https://ieeexplore.ieee.org/abstract/document/8334253). Scene change detection is not difficult to do.
