### ISSUE TITLE
RGB order of the pwc net!!!!!

### ISSUE THREAD

**Issue by Liupengshuaige** [baowenbo/DAIN#66]
wonderful job!!!!Here is my question:
[https://github.com/NVlabs/PWC-Net/tree/master/PyTorch](url)
the origin nvlab pwc-net reverse RGB channel  to BGR, while when I'm reading your code ,the img get from  imread by scipy.ndimage is RGB order , you use the RGB order img directly, so the pth from your project site is trained with RGB order ? or the RGB or BGR order doesn't have much effect on  flow estimation .
and the megadepth net is also the same?
Thank you

**Comment by baowenbo** [comment]
Yes, we have a mistake here, but according to our later test, the order sequence does not affect too much for optical flow accuracy, as well as interpolation accuracy.
Megadepth has no such problem.
