### ISSUE TITLE
How to run on windows？

### ISSUE THREAD

**Issue by fCenever** [baowenbo/DAIN#67]
How to run on windows？

**Comment by RF-Nelson** [comment]
You could try this: https://grisk.itch.io/dain-app

**Comment by fCenever** [comment]
thanks!
&nbsp;

影


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Richard Nelson"<notifications@github.com&gt;; 
发送时间: 2020年5月1日(星期五) 晚上8:03
收件人: "baowenbo/DAIN"<DAIN@noreply.github.com&gt;; 
抄送: "631707329"<631707329@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baowenbo/DAIN] How to run on windows？ (#67)





 
You could try this: https://grisk.itch.io/dain-app
