### ISSUE TITLE
Dockerfile for DAIN

### ISSUE THREAD

**Issue by micmelesse** [baowenbo/DAIN#71]
It would be nice if there was Dockerfile with all the dependencies.

**Comment by baowenbo** [comment]
Hey buddy, why not join us by adding a dockerfile thanks. ;-)

**Comment by micmelesse** [comment]
Haha, I am trying to do that using a PyTorch docker as a base. What are the critical dependencies in your opinion? I know there is an environment yaml. Is everything in there needed for DAIN to build?

**Comment by betegon** [comment]
Any update on this @micmelesse ?

I am not a docker proffesional, but maybe I can help you!

**Comment by micmelesse** [comment]
Hi @betegon, I am kind of stuck. I created a [branch](https://github.com/micmelesse/DAIN/tree/dockerfile ) in my fork with a dockerfile. It creates a conda environment using a cleaned up yaml file and then builds the packages using this command.
 
`docker build --network=host -t dain .`

You can enter the container with 

`docker run --ipc=host -it --rm --network=host --runtime=nvidia -w /DAIN`

This works, I can activate the conda environment with 

`source activate pytorch1.0.0`

 however when I try to run it

`python demo_MiddleBury.py`

I get an error 

`'ImportError: /opt/conda/envs/pytorch1.0.0/lib/python3.6/site-packages/filterinterpolation_cuda-0.0.0-py3.6-linux-x86_64.egg/filterinterpolation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd`

Looking around this seems to be because the application is finding the cuda of the container(10) and not the cuda in the conda environment (9). 

I tired using an older nvidia pytorch container with cuda 9 but that doesnot detect my gpu or the gpu in a aws p2x instance.

@baowenbo Any ideas about this?

**Comment by ZurMaD** [comment]
@micmelesse An the end you managed to dockerize the github, how could I use it?

**Comment by micmelesse** [comment]
@ZurMaD No, I have not. I just don't have the time to deal with it.

**Comment by ZurMaD** [comment]
Thanks for answer, I'll try next two weeks.

**Comment by Praevalens** [comment]
Hey there I actually made this docker file its over at my public fork of DAIN: https://gitlab.com/Miscoriadev/dain-fork-for-docker

It even works with with compute power 7.5 (Had to get my RTX 2080 Ti working)

**Comment by McFalljb** [comment]
@Praevalens Thank you for sharing

**Comment by micmelesse** [comment]
@Praevalens This is is awesome.  Thank you.

**Comment by iamyb** [comment]
Another repo support DAIN with docker, together with ESRGAN and DeOldify. Hope it helps
https://github.com/iamyb/DAIN_ESRGAN_DeOldify
