### ISSUE TITLE
[Errno 2] No such file or directory: './MiddleBurySet/other-data/'

### ISSUE THREAD

**Issue by fmbao** [baowenbo/DAIN#72]
报的这个错，other data的数据应该在哪儿下载到呢？

**Comment by baowenbo** [comment]
Download pretrained models,

$ cd model_weights
$ wget http://vllab1.ucmerced.edu/~wenbobao/DAIN/best.pth

and Middlebury dataset:

$ cd ../MiddleBurySet
$ wget http://vision.middlebury.edu/flow/data/comp/zip/other-color-allframes.zip
$ unzip other-color-allframes.zip
$ wget http://vision.middlebury.edu/flow/data/comp/zip/other-gt-interp.zip
$ unzip other-gt-interp.zip
$ cd ..
