### ISSUE TITLE
Some questions about running on Windows

### ISSUE THREAD

**Issue by BigQiBrother** [baowenbo/DAIN#8]
When I run build.sh in DAIN on windows,
D:\python3.7\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7): fatal error C1021: ▒▒Ч▒▒Ԥ▒▒▒▒▒▒▒▒▒warning▒▒
D:\python3.7\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
error: command 'D:\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
But I have configured path for cl.exe,can someone guide me? Thanks!!!!!!!!

**Comment by baowenbo** [comment]
I never tried the code on Windows, there might be some problems.

**Comment by BigQiBrother** [comment]
Thank you very much, I used Ubuntu to run successfully in the afternoon. I am still only looking at the stage of the paper running model. I will try hard to study it again, thank you again.



------------------ 原始邮件 ------------------
发件人: "Wenbo Bao"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 晚上10:14
收件人: "baowenbo/DAIN"<DAIN@noreply.github.com>; 
抄送: "好吗？好的。"<1591535327@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [baowenbo/DAIN] Some questions about running on Windows (#8)




I never tried the code on Windows, there might be some problems.
